---
# Check the README for a more specific explanation
user@host:
  - [ "db", "location on vm", "location on local", "15", 3] # Every 15 days, keep the 3 most recents
  - [ "tar", "location on vm", "location on local", "10", 3] # Every 10 days, keep the 3 most recents
  - [ "dir", "location on vm", "location on local", "1MONTH", 1] # The first of every month, keep the most recent only
  - [ "file", "location on vm", "location on local", "2MONTH", 1] # The first of every two months, keep the most recent only